version: '3.4'
services:
  flexo-server:
    container_name: flexo-server
    image: nroi/flexo
    restart: always
    networks:
      - web
    environment:
      - RUST_LOG=debug
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7878/status || exit 1"]
      interval: 60s
      timeout: 120s
      retries: 5
      start_period: 1s
    labels:
      - traefik.enable=true
      - traefik.http.routers.flexo.rule=Host(`flexo.internal.blitzaxt.com`)
      - traefik.http.routers.flexo.tls=true
      - traefik.http.services.flexo.loadbalancer.server.port=7878
      - traefik.http.middlewares.test-ipallowlist.ipallowlist.sourceRange=100.64.0.0/10, 192.168.0.0/24
    volumes:
      - /mnt/storage1/docker/flexo_cache:/var/cache/flexo

networks:
  web:
    external: true
